S3_BUCKET: <%=ENV["S3_BUCKET"]%>
AWS_ACCESS_KEY_ID: <%=ENV["AWS_ACCESS_KEY_ID"]%>
AWS_SECRET_ACCESS_KEY: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
AWS_BUCKET: <%=ENV["S3_BUCKET"]%>
S3_BUCKET_PROD: <%=ENV["S3_BUCKET_PROD"]%>
AWS_BUCKET_PROD: <%=ENV["S3_BUCKET_PROD"]%>
